### ISSUE TITLE
Add support for PGTEI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jhellingman/tei2html#23]
Tei2html does not support PGTEI, as used by Project Gutenberg volunteers.

Minimal support will be needed for the following:

1. Understand unnumbered `<div>` elements. (DONE)
2. Understand plain CSS in `@rend` attributes. (should be a flag, consider pre-processing and use of `@style` attribute; `@style` support DONE.)
3. Understand `<pgExtensions>` elements.
4. Handle `<q>` elements by inserting quotation marks. (should be a flag; a big issue here is that `<q>` elements are often used as wrappers for elements that do not directly fit the structure of a TEI document, as to make them valid. We somehow need to distinguish those uses from the intended usage of text between quotation marks.)
5. Handle the various `<divGen>` types. (Partly DONE)

Original issue reported on code.google.com by `jhellingman` on 24 Mar 2011 at 10:50

**Comment by jhellingman** [comment]
Project Gutenberg made pgtei obsolete.
