### ISSUE TITLE
Can't locate SgmlSupport.pm

### ISSUE THREAD

**Issue by honza** [jhellingman/tei2html#36]
```
$ git clone https://github.com/jhellingman/tei2html
$ cd tei2html/tools
$ perl tei2html.pl
Can't locate SgmlSupport.pm in @INC (you may need to install the SgmlSupport module) (@INC contains: /usr/local/lib64/perl5/5.30 /usr/local/share/perl5/5.30 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at tei2html.pl line 14.
BEGIN failed--compilation aborted at tei2html.pl line 14.
```

Why isn't Perl loading the file from the current directory?

**Comment by jhellingman** [comment]
For the perl question: https://stackoverflow.com/questions/46549671/doesnt-perl-include-current-directory-in-inc-by-default

To get it to work, you can copy the files in /tools ending in  .pm to your local perl installation, <PERL installation path>\perl\site\lib

Jeroen.
